### ISSUE TITLE
Setup Help

### ISSUE THREAD

**Issue by ikrowni** [erobin27/BetBot#1]
Hello and thank you very much for this awesome project. I'm really looking forward to getting this all setup and was hoping i could get some help.

> To get started clone the repo to your local machine and begin installing it's dependencies

What dependencies need to be installed?

> You will need to setup your discord token and database connection info in a .env file in the project directory.

Can you give an example of how the .env file is to be setup?

I've never used MySQL before is there any further setup needed past just installing it? If so could you provide a quick tutorial on what steps to take in order to get the bot connected with mysql?

EDIT: After installing mysql i created a new database with the name UFC_BOT I added a username and password to the DB. But I'm still not sure about how the env file is supposed to be setup

EDIT2: I created a .env file using this information

```
APPID=MYID
TOKENTEST=MYTOKEN
user=MYUSERNAME
passwd=MYPASSWORD
database=UFC_BOT
```

I also installed each dependency it complained about when trying to run `python BetBot.py`

Now when i run `python BetBot.py` i get the following error.

```
C:\Discord_Bots\BetBot>python BetBot.py
Traceback (most recent call last):
  File "C:\Discord_Bots\BetBot\BetBot.py", line 7, in <module>
    import Database
  File "C:\Discord_Bots\BetBot\Database.py", line 5, in <module>
    db = mysql.connector.connect(
  File "C:\Users\THEKI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mysql\connector\__init__.py", line 274, in connect
    return MySQLConnection(*args, **kwargs)
  File "C:\Users\THEKI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mysql\connector\connection.py", line 115, in __init__
    self.connect(**kwargs)
  File "C:\Users\THEKI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mysql\connector\abstracts.py", line 1015, in connect
    self._open_connection()
  File "C:\Users\THEKI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mysql\connector\connection.py", line 429, in _open_connection
    self._do_auth(self._user, self._password,
  File "C:\Users\THEKI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mysql\connector\connection.py", line 230, in _do_auth
    self._auth_switch_request(username, password)
  File "C:\Users\THEKI\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\mysql\connector\connection.py", line 381, in _auth_switch_request
    raise errors.get_exception(packet)
mysql.connector.errors.ProgrammingError: 1045 (28000): Access denied for user ''@'localhost' (using password: NO)
```

Now i'm stuck again but feel like im getting much closer.

**Comment by tcprescott** [comment]
When you create the database user, you need to specify localhost.

Example:

`create user MYUSERNAME@localhost identified by 'MYPASSWORD';`

then grant all to it

`grant ALL on UFC_BOT.* to MYUSERNAME@localhost;`

**Comment by ikrowni** [comment]
> When you create the database user, you need to specify localhost.
> 
> Example:
> 
> `create user MYUSERNAME@localhost identified by 'MYPASSWORD';`
> 
> then grant all to it
> 
> `grant ALL on UFC_BOT.* to MYUSERNAME@localhost;`

I've done those steps already but still get the same error i pasted above

**Comment by etr-dev** [comment]
Sorry when I made this I did not make it very friendly for others to setup😂 I did not use the script to setup the database like how it looks in Python.

Honestly if you want to use BetBot I can give you a link for it to join your discord server. Setting it up locally is pretty tough with regards to the database.

**Comment by ikrowni** [comment]
> Honestly if you want to use BetBot I can give you a link for it to join your discord server. Setting it up locally is pretty tough with regards to the database.

That would be awesome and much appreciated.

**Comment by etr-dev** [comment]
> > Honestly if you want to use BetBot I can give you a link for it to join your discord server. Setting it up locally is pretty tough with regards to the database.
> 
> That would be awesome and much appreciated.

No problem, give me some time. I will redo the DB because right now it isn't very stable. Then I'll put a link to add it to your server on the readme

**Comment by etr-dev** [comment]
> > Honestly if you want to use BetBot I can give you a link for it to join your discord server. Setting it up locally is pretty tough with regards to the database.
> 
> That would be awesome and much appreciated.

I have added the link to the readme to invite the bot to your server. Currently you start with $500 and cannot earn more other than winning bets. I plan on making a daily reward you can claim either tomorrow or this weekend.

**Comment by ikrowni** [comment]
Thank you very much for the bot and the assistance I'm looking forward to checking it out.

**Comment by ikrowni** [comment]
When I try to add the bot I get an error.

(This integration is private. Only the application owner can add it.)

**Comment by etr-dev** [comment]
> When I try to add the bot I get an error.
> 
> 
> 
> (This integration is private. Only the application owner can add it.)

I think I fixed it. It should work for you now. (Hopefully)

**Comment by ikrowni** [comment]
Alright the bot was added to my server. I typed >menu and the bot said it created an account for me. I type >menu again and clicked (Upcoming Event) but it is presenting me with UFC 267 card rather than the next upcoming card.

Edit: okay it's working now guess I just had to wait until closer until the actual event time.
