### ISSUE TITLE
Betting is for the previous week instead of current

### ISSUE THREAD

**Issue by ikrowni** [erobin27/BetBot#4]
When i try to place a bet in for UFC 268 im getting the results for UFC 267 instead.

![image](https://user-images.githubusercontent.com/4442098/140627474-0d06ee30-233c-4d3c-9bdd-1abb0f88085e.png)

**Comment by etr-dev** [comment]
UFC.com events page was messing up, it kept going blank and not showing the latest fights. switched it to look at the tickets page instead and it fixed. Not a good fix but I'll keep looking into how to keep it from messing up when the UFCs website goes crazy

**Comment by ikrowni** [comment]
Awesome just wanted to bring awareness
